#! /usr/bin/perl

eval "exec perl -S $0 $@"
	if 0 ;

## Renames files based on regexp
## Actually, this can do much more than just renaming ..

$0 =~ s!/.*/(.*)$!$1!g ;

$Usage = "$0 perlexpr [files]\n" ;

die $Usage unless ($op = shift) ;

if (!@ARGV) {
	@ARGV  = <STDIN> ;
	chop(@ARGV) ;
}

for (@ARGV) {
	$was = $_ ;
	eval "$op" ;
	die $@ if $@ ;
	rename($was, $_) unless $was eq $_ ;
}

0;
